### ISSUE TITLE
Add documentation for psutil dependencies

### ISSUE THREAD

**Issue by djmgit** [djmgit/SaberX#10]
According to psutil documentation, it has the following two dependencies:
- gcc
- python3-dev

python3-dev has to be present in requirements.txt before psutil.
Although gcc should be present on most systems by default, still it can be mentioned in the doc:

something like:

Run ```sudo apt install build-essential ```
or just a simple mention that ```Your system should contain gcc```

After the gcc is available in the system, requirements.txt packages should be installed.

**Comment by Mis2** [comment]
Hi, I want to work on this issue. I am new to the world of open-source contributions but I think this will provide me the perfect opportunity to test the waters.
