### ISSUE TITLE
Fix .flake8 lint errors: code E101

### ISSUE THREAD

**Issue by ghost** [djmgit/SaberX#11]
I'm fixing the .flake linting errors for code E101, referring to #6.

**Comment by djmgit** [comment]
@britho great :+1: 

Also, I too was wondering about the build release versioning. The ```1.0``` version present in setup.py just indicates the initial start of the project and is merely a place holder.

**Semantic Versioning** looks good to me and I am thinking of moving ahead with the same.
Feel free to reset the version in setup.py :)

Also I will be soon creating a release on github and PyPi once some of the remaining doc changes are done.

**Comment by ghost** [comment]
Awesome!  Sounds good.
