### ISSUE TITLE
Remove lint errors

### ISSUE THREAD

**Issue by djmgit** [djmgit/SaberX#6]
As of now there are plenty of lint errors in SaberX. These errors needs to be fixed.

Steps
- open .flake8 file present at the root of the project.
- remove one rule from the ignore list.
- run ```flake8```
- Solve the errors reported by flake8
- Open an issue for the rule you are fixing (one rule per issue)
- Refer this issue there
- Send a PR. In the PR too, refer this issue as parent.
- Comment that you are working on it.

**Comment by ghost** [comment]
Going to fork the repo and take this up when I get some free time today and the rest of this week.  Looking forward for contributing to the project.

**Comment by djmgit** [comment]
@britho Thats great!, looking forward for your PR :)

**Comment by ghost** [comment]
This one is complete. This is my personal account outside of my company-associated Github profile. FYI :)

**Comment by djmgit** [comment]
@ordus closing this :)
Also you might want to have a look at this #5 . I have not quite found the time recently to dig into it. You can take it up if you find it interesting :)
